// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuymgkqkvwixukutvabw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1eW1na3FrdndpeHVrdXR2YWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjU2OTEsImV4cCI6MjA2NjM0MTY5MX0.eFA3V3DNEvEUZII_gnRRrPp_953buQXYpBieYRS7Hdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);